const Des23 = {
    Img1: require('../../assets/images/des23/1.JPG'),
    Img2: require('../../assets/images/des23/2.JPG'),
    Img3: require('../../assets/images/des23/3.JPG'),
    Img4: require('../../assets/images/des23/4.JPG'),
    Img5: require('../../assets/images/des23/5.JPG'),
    Img6: require('../../assets/images/des23/6.JPG'),
    Img7: require('../../assets/images/des23/7.JPG'),
    Img8: require('../../assets/images/des23/8.JPG'),
    Img9: require('../../assets/images/des23/9.JPG'),
    Img10: require('../../assets/images/des23/10.jpg'),
    Img11: require('../../assets/images/des23/11.JPG'),
    Img12: require('../../assets/images/des23/12.JPG'),
    Img13: require('../../assets/images/des23/13.JPG'),
    Img14: require('../../assets/images/des23/14.JPG'),
    Img15: require('../../assets/images/des23/15.JPG'),
    Img16: require('../../assets/images/des23/16.JPG'),
    Img17: require('../../assets/images/des23/17.JPG'),
    Img18: require('../../assets/images/des23/18.JPG'),
    Img19: require('../../assets/images/des23/19.JPG'),
    Img20: require('../../assets/images/des23/20.JPG'),
    Img21: require('../../assets/images/des23/21.JPG'),
    Img22: require('../../assets/images/des23/22.JPG'),
    Img23: require('../../assets/images/des23/23.JPG'),
    Img24: require('../../assets/images/des23/24.JPG'),
    Img25: require('../../assets/images/des23/25.JPG'),
    Img26: require('../../assets/images/des23/26.JPG'),
    Img27: require('../../assets/images/des23/27.JPG'),
    Img28: require('../../assets/images/des23/28.JPG'),
    Img29: require('../../assets/images/des23/29.JPG'),
    Img30: require('../../assets/images/des23/30.JPG'),
    Img31: require('../../assets/images/des23/31.JPG'),
    Img32: require('../../assets/images/des23/32.JPG'),
    Img33: require('../../assets/images/des23/33.JPG'),
    Img34: require('../../assets/images/des23/34.JPG'),
    Img35: require('../../assets/images/des23/35.JPG'),
    Img36: require('../../assets/images/des23/36.JPG')
}

export default Des23